name: hinf
channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - snakemake=8.25.5
 - conda=24.4.0
 - numpy
 - xarray
 - dask[array] >= 2023.01.0
 - distributed >= 2023.01.0
 - dask-ml
 - scipy
 - typing-extensions
 - numba
 - zarr >= 2.10.0, != 2.11.0, != 2.11.1, != 2.11.2
 - fsspec != 2021.6.*
 - scikit-learn
 - pandas
 - openpyxl=3.1.4
 - plotly
 - seaborn
 - matplotlib
 - jupyterlab
 - pip:
   - sgkit[vcf]